/**
 * Completed transactions — the real dataset.
 *
 * Source: the closed-transactions workbook (Google Sheets), which is the
 * business record and therefore authoritative for neighborhood, property type,
 * builder, side, and closing month.
 *
 * WHERE THE WORKBOOK AND ZILLOW DISAGREE, THE WORKBOOK WINS. Several reviews
 * carry a Zillow-generated transaction line naming a different neighborhood
 * ("Idlewild Farms" where the workbook says Easthaven) or even a different
 * property type. Zillow's line is an approximation generated by the platform;
 * the workbook is taken from the closing. Rows carrying a `reviewId` whose
 * Zillow line disagrees are marked below so nobody "fixes" them back.
 *
 * ---------------------------------------------------------------------------
 * NOT CARRIED ACROSS FROM THE WORKBOOK, EVER:
 *
 *   Street addresses — every buyer-side row would publish where a client lives.
 *   Closing prices    — no price field on this type by design. The figures live
 *                       in ./internal-metrics.ts, which no page may import.
 *   Client names      — the ledger names nobody. The review join carries an
 *                       abbreviated byline and that is the only name a visitor
 *                       ever sees.
 *
 * Dollar figures in the workbook's Highlights and Concessions columns are
 * reduced to the KIND of thing negotiated. CLAUDE.md §7 attaches the results
 * disclaimer to the number, not to the fact, and a test greps every lever
 * for "$".
 * ---------------------------------------------------------------------------
 */

import type { Transaction } from "./types";

export const TRANSACTIONS: readonly Transaction[] = [
  /* ------------------------------------------------------------------ 2026 */
  {
    id: "2026-ayrsley-01",
    side: "seller",
    year: 2026,
    month: 10,
    neighborhood: "Ayrsley",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    builder: "Lennar",
    /* Neighborhood column: Steele Creek, exact match. Ayrsley is the same
       community named in AREAS-SPEC.md §10 as where she lives — a different
       household's home, in the same mixed-HOA development, not hers. That
       distinction is why this row is unremarkable under §10's "her home is
       not a case study" rule: it names someone else's closing. */
    market: "steele-creek",
    pillars: ["sellers"],
    /* Workbook: "Multiple showings in one weekend. Under contract in 7 days.
       Sold for 99% of list price." Figure dropped for the reason given on
       Turtle Rock and Trinity Park, above; the showings-to-contract speed
       carries no number and is the real lever. */
    lever: "Multiple showings in one weekend, under contract in seven days.",
    /* Left Review: Y, but the sheet's Reviews cell is blank — no text to
       transcribe. Same open-ended state as Jonathan Fitch's row before that
       one was corrected; flagged in CLAUDE.md §12 rather than guessed at. */
  },
  {
    id: "2026-arvin-hills-01",
    side: "seller",
    year: 2026,
    month: 8,
    neighborhood: "Arvin Hills",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    /* Relocation column: Y — a seller relocating away, not a buyer relocating
       in. The pillar has meant either direction since the column was added
       (see 2024-cresswind-01 and 2023-easthaven-01 for the buyer-side use). */
    pillars: ["sellers", "relocation"],
    /* Workbook's Neighborhood (submarket-evidence) column is blank, and the
       Submarket value is "North Charlotte" — not "Northwest Charlotte" — so
       this stays unmapped for the same reason Carlton Hills, Brownes Ferry,
       and Katelyn Moors do (CLAUDE.md §5, 2026-08-31). */
    lever: "An estate sale for an out-of-town client, under contract inside a month.",
  },
  {
    id: "2026-turtle-rock-01",
    side: "seller",
    year: 2026,
    month: 8,
    neighborhood: "Turtle Rock",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["sellers"],
    /* Submarket column: East Charlotte, exact match. */
    market: "east-charlotte",
    /* Workbook (2026-09-09 update) added "Sold for 99% of list price. Went
       under contract in just 3 weeks." on top of the estate sale already
       recorded. The percentage is dropped by the same discipline that drops a
       dollar figure — it is a quantified outcome for one closing, and the site
       treats those as needing a disclaimer it does not carry here (§7; see how
       the reviews schema flags "quantified financial outcome" even without a
       literal $). Speed survives because it names no number. */
    lever: "An estate sale, under contract in three weeks.",
    reviewId: "unverified-aime-barron",
  },
  {
    id: "2026-trinity-park-01",
    side: "seller",
    year: 2026,
    month: 8,
    neighborhood: "Trinity Park",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["sellers"],
    /* Submarket column: Northwest Charlotte, exact match. */
    market: "northwest-charlotte",
    /* Workbook (2026-09-09): "Under contract in less than 2 weeks... Helped an
       investor sell his flip." The 96.2%-of-list figure is dropped for the
       same reason as Turtle Rock's, above — selling an investor's flip fast is
       the genuinely distinctive fact and it carries no number. No review was
       left on this one (Left Review: N). */
    lever: "Sold an investor's flip, under contract inside two weeks.",
  },
  {
    id: "2026-edgewater-01",
    side: "buyer",
    year: 2026,
    month: 8,
    neighborhood: "Edgewater",
    city: "Lancaster",
    state: "SC",
    propertyType: "Single Family",
    builder: "True Homes",
    /* Relocating from New York — the workbook's new Relocation column, which
       is the first time that pillar has had a source other than a review. */
    pillars: ["new-construction", "relocation", "carolinas-border"],
    /* Workbook (2026-09-09) added Highlights and a review that were both blank
       before: "Buyers received full home furniture (model home) and purchased
       below comps for the neighborhood." Neither clause names a figure, so
       both survive as stated — "below comps" is a comparison, not a number. */
    lever:
      "Out-of-state buyers. Builder concessions at closing, the model home's furniture included, and a price below the neighborhood's comps.",
    reviewId: "unverified-yvon",
  },
  {
    id: "2026-annsborough-park-01",
    side: "buyer",
    year: 2026,
    month: 8,
    neighborhood: "Annsborough Park",
    city: "Concord",
    state: "NC",
    propertyType: "Single Family",
    builder: "M/I Homes",
    pillars: ["new-construction"],
    /* The fullest lever in the ledger, and the clearest illustration of the
       USP: a rate buydown is exactly the lever a first-time buyer does not
       know exists. Structure only — the rates and the dollar figures stay in
       internal-metrics. */
    lever:
      "A builder-funded 2-1 rate buydown, with the seller covering the reduced rate for the remaining years, on top of a price under list.",
  },
  {
    id: "2026-english-trails-01",
    side: "buyer",
    year: 2026,
    month: 4,
    neighborhood: "English Trails",
    city: "Fort Mill",
    state: "SC",
    /* city is the market */
    market: "fort-mill",
    propertyType: "Single Family",
    pillars: ["carolinas-border"],
    /* Workbook: "a back to back transaction" — under contract on this house
       while their existing home was still being prepared for market. Sequencing
       two moves so neither waits on the other is a lever in its own right, and
       it is not a price. */
    lever:
      "A back-to-back move: under contract on this house while their existing home was still being prepared for market.",
    /* Her second purchase with Jasmine, four years after 2022-beverly-crest-01.
       The repeat is the argument; see that row and this review's pair. */
    reviewId: "zillow-brittany-turner-2026",
  },

  {
    id: "2026-windsor-park-01",
    side: "buyer",
    year: 2026,
    month: 7,
    neighborhood: "Windsor Park",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    /* Relocating from Florida. */
    pillars: ["relocation"],
    /* Submarket column: East Charlotte, exact match. */
    market: "east-charlotte",
    /* Workbook: under list, plus concessions. The client's own review adds
       what the concessions were FOR — foundation work the house needed — which
       is the part worth having, and it carries no figure. */
    lever: "Purchased under list price, with concessions covering foundation work the house needed.",
    reviewId: "google-matthew-swecker",
  },
  {
    id: "2026-charlotte-01",
    side: "seller",
    year: 2026,
    month: 6,
    /* Workbook records no neighborhood; locationLabel degrades to city, state. */
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["sellers"],
    /* An estate sale run for a client living in another state — two things at
       once that put distance between the seller and the house. */
    lever: "An estate sale, run for a client living out of state.",
    /* No reviewId: his review is recorded at unverified-john-white and is
       gated until someone finds the original. */
  },
  {
    id: "2026-providence-plantation-01",
    side: "buyer",
    year: 2026,
    month: 6,
    neighborhood: "Providence Plantation",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    /* Relocating from Florida. */
    pillars: ["relocation"],
    /* The lever continues AFTER closing: repairs negotiated at inspection, then
       coordinated with the contractors once the clients were mid-move. Most
       buyers do not know that table exists. */
    lever:
      "Purchased under list price with seller concessions, and the negotiated repairs were coordinated with contractors after closing.",
    reviewId: "google-lee-cottrell",
  },
  {
    id: "2026-wynfield-forest-01",
    side: "buyer",
    year: 2026,
    month: 6,
    neighborhood: "Wynfield Forest",
    city: "Huntersville",
    state: "NC",
    propertyType: "Single Family",
    pillars: [],
    /* The clearest lever on the page: three separate items conceded, none of
       them price. Exactly the §2 argument. */
    lever: "A full roof replacement, HVAC servicing, and the refrigerator, all conceded by the seller.",
    reviewId: "zillow-chandler-cordes",
  },
  {
    id: "2026-masons-bend-01",
    side: "seller",
    year: 2026,
    month: 5,
    neighborhood: "Masons Bend",
    city: "Fort Mill",
    state: "SC",
    /* city is the market */
    market: "fort-mill",
    propertyType: "Single Family",
    pillars: ["sellers", "carolinas-border"],
    /* Workbook: multiple offers inside 48 hours, closed above list. The client's
       review is explicit that the winning offer was chosen on TERMS rather than
       the top number, which is the seller-side version of the whole argument. */
    lever:
      "Multiple offers inside 48 hours. The one accepted was chosen on its terms, not its number, and it closed above list price.",
    reviewId: "zillow-sophie-fox",
  },
  {
    id: "2026-sloan-station-01",
    side: "buyer",
    year: 2026,
    month: 5,
    neighborhood: "Sloan Station",
    city: "Charlotte",
    state: "NC",
    propertyType: "Townhouse",
    builder: "Mungo Homes",
    pillars: ["new-construction"],
    /* Workbook: "Showed up to the closing table with no money down and a
       refund." No figure attached, so it ships as stated. */
    lever: "First-time buyers who brought no money to the closing table and left with a refund.",
    /* Her brother. He discloses it in his own first sentence, which is why the
       review is publishable at all — see lib/reviews. */
    reviewId: "google-josh-garcia",
  },
  {
    id: "2026-beverly-crest-02",
    side: "seller",
    year: 2026,
    month: 4,
    neighborhood: "Beverly Crest",
    city: "Charlotte",
    state: "NC",
    propertyType: "Townhouse",
    pillars: ["sellers"],
    lever: "On the market sixteen days.",
    /* THE SAME TOWNHOUSE AS 2022-beverly-crest-01, sold four years after she
       helped them buy it — and in the same month she got them under contract in
       Fort Mill (2026-english-trails-01). One client, three rows, four years.
       That arc is the strongest retention evidence in the dataset.

       The review covers the purchase and the sale together, so it is linked
       from both rows deliberately. */
    reviewId: "zillow-brittany-turner-2026",
  },
  {
    id: "2026-shannon-park-02",
    side: "seller",
    year: 2026,
    month: 3,
    neighborhood: "Shannon Park",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["sellers"],
    /* Submarket column: East Charlotte, exact match. */
    market: "east-charlotte",
  },

  /* ------------------------------------------------------------------ 2024 */
  {
    id: "2024-tega-cay-01",
    side: "buyer",
    year: 2024,
    month: 5,
    /* Workbook records no subdivision, neighborhood, or submarket for this
       row — the thinnest entry in the ledger. locationLabel() degrades to
       city, state. */
    city: "Tega Cay",
    state: "SC",
    propertyType: "Townhouse",
    /* city is the market. Tega Cay's first row — CLAUDE.md §5 and
       AREAS-SPEC.md §12 both listed it at zero evidence until this one. */
    market: "tega-cay",
    pillars: ["carolinas-border"],
    /* No Highlights, no review, no concessions in the sheet. A row without a
       lever is still evidence that the closing happened; nothing here is
       invented to fill the gap. */
  },
  {
    id: "2024-patriots-crossing-01",
    side: "seller",
    year: 2024,
    month: 10,
    neighborhood: "Patriots Crossing",
    city: "Clover",
    state: "SC",
    propertyType: "Single Family",
    pillars: ["sellers", "carolinas-border"],
    /* Neighborhood column: "Lake Wylie / Bethel" — and Clover, the closing's city, is lake-wylie's own postal city in markets.ts. */
    market: "lake-wylie",
    lever: "Under contract in four days.",
  },
  {
    id: "2024-loso-terraces-01",
    side: "buyer",
    year: 2024,
    month: 4,
    /* Workbook: LoSo Terraces. Both linked reviews' Zillow lines say "York
       Road" — the workbook is the closing record and wins. */
    neighborhood: "LoSo Terraces",
    city: "Charlotte",
    state: "NC",
    propertyType: "Townhouse",
    builder: "Hopper Communities",
    /* Relocation from Chicago, documented in both clients' own reviews. */
    pillars: ["new-construction", "relocation"],
    /* Subdivision "LoSo Townhomes", Neighborhood "Lower South End (LoSo)" — both name the market directly. */
    market: "loso",
    lever: "Out-of-state buyers who toured for one weekend and bought at the end of it.",
    /* Two reviews, one from each half of the couple, already linked to each
       other by sameTransactionAs. Never run both on a page — linking the
       publishable one. */
    reviewId: "zillow-danielle-bonaccorso",
  },
  {
    id: "2024-cresswind-01",
    side: "buyer",
    year: 2024,
    month: 3,
    neighborhood: "Cresswind",
    city: "Mint Hill",
    state: "NC",
    propertyType: "Single Family",
    builder: "Kolter Homes",
    /* Relocating from Tennessee — from the workbook's Relocation column, which
       documents it where the review does not mention it. */
    pillars: ["new-construction", "relocation"],
    reviewId: "google-julie-counterman",
  },

  /* ------------------------------------------------------------------ 2023 */
  {
    id: "2023-the-providence-01",
    side: "buyer",
    year: 2023,
    month: 12,
    /* Workbook: The Providence, townhome. The linked review's Zillow line says
       "Olde Providence South" and single family — wrong on both counts. */
    neighborhood: "The Providence",
    city: "Charlotte",
    state: "NC",
    propertyType: "Townhouse",
    builder: "Meeting Street Homes and Communities",
    pillars: ["new-construction"],
    lever: "Won in a multiple-offer situation.",
    reviewId: "zillow-pavel-volynskiy",
  },
  {
    id: "2023-moores-chapel-village-01",
    side: "seller",
    year: 2023,
    month: 12,
    neighborhood: "Moores Chapel Village",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["sellers"],
    /* Submarket column: Northwest Charlotte, exact match. */
    market: "northwest-charlotte",
    reviewId: "zillow-david-godfrey",
  },
  {
    id: "2023-brownes-ferry-01",
    side: "seller",
    year: 2023,
    month: 11,
    neighborhood: "Brownes Ferry",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["sellers"],
  },
  {
    id: "2023-preston-park-01",
    side: "buyer",
    year: 2023,
    month: 9,
    neighborhood: "Preston Park",
    city: "Pineville",
    state: "NC",
    /* city is the market */
    market: "pineville",
    propertyType: "Single Family",
    builder: "Meritage Homes",
    /* Relocation is documented in the client's own review — out of state, and
       five or six houses toured in a single day because of it. */
    pillars: ["new-construction", "relocation"],
    lever: "Out-of-state buyers touring in a single day. Builder concessions, and a price under list.",
    reviewId: "google-nuraini-adams",
  },
  {
    id: "2023-lancaster-01",
    side: "buyer",
    year: 2023,
    month: 9,
    /* Workbook records no neighborhood; locationLabel degrades to city, state. */
    city: "Lancaster",
    state: "SC",
    propertyType: "Single Family",
    pillars: ["carolinas-border"],
    lever: "Won in a multiple-offer situation.",
    reviewId: "google-amy-hood",
  },
  {
    id: "2023-riverfront-01",
    side: "buyer",
    year: 2023,
    month: 8,
    neighborhood: "Riverfront",
    city: "Mount Holly",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["relocation"],
    lever: "Relocating from Florida. Purchased under list price, with seller concessions on top.",
    reviewId: "zillow-tanner-mathewson",
  },
  {
    id: "2023-waterlyn-01",
    side: "seller",
    year: 2023,
    month: 8,
    neighborhood: "Waterlyn",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["sellers"],
    /* Neighborhood column: Steele Creek, exact match — confirmed by Bill 2026-08-31: off Shopton Rd, considered Southwest Charlotte. */
    market: "steele-creek",
    lever: "Under contract in one day.",
  },
  {
    id: "2023-walnut-creek-01",
    side: "seller",
    year: 2023,
    month: 6,
    neighborhood: "Walnut Creek",
    city: "Lancaster",
    state: "SC",
    propertyType: "Single Family",
    pillars: ["sellers", "carolinas-border"],
    /* Neighborhood column: "Indian Land Perimeter" — and the client's own review says "sold our home in Lancaster/Indian Land." */
    market: "indian-land",
    /* The lever is sourced from the workbook's review text for this closing,
       which is a FAMILY member's account — these are her parents. Kept
       deliberately (Bill, 2026-08-17): the facts are facts about the
       transaction, and holding a sale together is a seller-side lever that has
       nothing to do with list price, which is why it earns its place. The
       review it came from stays withheld; the lever is ours, not a quote. */
    lever: "The buyers came close to walking during the contract period. The sale held together to closing.",
    /* Deliberately kept although it renders NOTHING today: the review is
       `withheld` (her mother, undisclosed in the text — see lib/reviews), and
       publishableReviewById suppresses the link. If that decision is ever
       reversed the join is already correct. */
    reviewId: "zillow-jennifer-garcia",
  },
  {
    id: "2023-concord-01",
    side: "buyer",
    year: 2023,
    month: 6,
    city: "Concord",
    state: "NC",
    propertyType: "Single Family",
    pillars: ["relocation"],
    lever: "Bought on virtual tours from out of the area, and won in a multiple-offer situation.",
    /* Resolved 2026-08-17: the Zillow byline "Maggie Jean" is her first and
       middle name; Brewer is the surname the workbook records. One person. */
    reviewId: "zillow-maggie-jean",
  },
  {
    id: "2023-shopton-point-01",
    side: "buyer",
    year: 2023,
    month: 5,
    neighborhood: "Shopton Point",
    city: "Charlotte",
    state: "NC",
    /* confirmed by Bill 2026-08-19 */
    market: "steele-creek",
    propertyType: "Single Family",
    builder: "Meritage Homes",
    pillars: ["new-construction"],
    lever: "Builder concessions at closing.",
    reviewId: "google-charay-bland",
  },
  {
    id: "2023-mountainbrook-01",
    side: "buyer",
    year: 2023,
    month: 4,
    neighborhood: "Mountainbrook",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: [],
    lever: "Seller concessions at closing.",
  },
  {
    id: "2023-lexington-commons-01",
    side: "buyer",
    year: 2023,
    month: 3,
    neighborhood: "Lexington Commons",
    city: "Rock Hill",
    state: "SC",
    /* city is the market */
    market: "rock-hill",
    propertyType: "Townhouse",
    pillars: ["carolinas-border"],
    lever: "Seller concessions at closing.",
    reviewId: "zillow-andrew-korpics",
  },
  {
    id: "2023-easthaven-01",
    side: "buyer",
    year: 2023,
    month: 1,
    neighborhood: "Easthaven",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    /* Relocating from South Carolina — a short move, but a state line and two
       sets of rules, which is what the pillar is about. */
    pillars: ["relocation"],
    /* Submarket column: East Charlotte, exact match. */
    market: "east-charlotte",
    lever: "Purchased under list price.",
  },

  /* ------------------------------------------------------------------ 2022 */
  {
    id: "2022-carlton-hills-01",
    side: "buyer",
    year: 2022,
    month: 12,
    /* Carlton Hills subdivision, within the wider Nevin community area. */
    neighborhood: "Carlton Hills",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    builder: "Northway Homes",
    pillars: ["new-construction"],
    /* Under list on a NEW BUILD is the noteworthy part — builders hold list
       price far harder than individual sellers do. */
    lever: "New construction purchased under the builder's list price.",
  },
  {
    id: "2022-easthaven-01",
    side: "buyer",
    year: 2022,
    month: 11,
    /* Workbook: Easthaven. The linked review's Zillow line says "Idlewild
       Farms" — the workbook is the closing record and wins. */
    neighborhood: "Easthaven",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: [],
    /* Submarket column: East Charlotte, exact match. */
    market: "east-charlotte",
    lever: "Purchased under list price, with seller concessions on top.",
    reviewId: "zillow-shayna-quilty-yoder",
  },
  {
    id: "2022-katelyn-moors-01",
    side: "buyer",
    year: 2022,
    month: 11,
    /* Workbook: Katelyn Moors. Both linked reviews' Zillow lines say
       "Prosperity Village". */
    neighborhood: "Katelyn Moors",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    /* Relocation documented in the clients' own words — one review says they
       were moving from out of state, the other names Phoenix. */
    pillars: ["relocation"],
    lever: "Out-of-state buyers who saw the house once. Purchased under list price, with seller concessions on top.",
    /* Two reviews describe this one closing and must never both run on a page.
       Linking the Phoenix one; its pair is zillow-cori-halter. */
    reviewId: "zillow-kathy-hannan",
  },
  {
    id: "2022-southpark-01",
    side: "buyer",
    year: 2022,
    month: 9,
    /* The unit is in the Piedmont Row complex; the neighborhood recorded here
       is SouthPark, deliberately one level up. Naming a single condo complex
       alongside a month and a property type narrows toward the individual
       buyer, which is the same privacy line the street-address rule draws. */
    neighborhood: "SouthPark",
    city: "Charlotte",
    state: "NC",
    /* subdivision name is the market name */
    market: "southpark",
    propertyType: "Condo",
    pillars: [],
    lever: "Purchased under list price.",
  },
  {
    id: "2022-park-place-01",
    side: "buyer",
    year: 2022,
    month: 9,
    neighborhood: "Park Place",
    city: "Dallas",
    state: "NC",
    propertyType: "Townhouse",
    pillars: [],
    /* No reviewId deliberately. Her review is verified and real
       (google-vicki-white) but gated on content, not provenance — it attacks
       the opposing agent and raises the client's veteran status. Linking it
       would point at something /reviews does not show. */
  },
  {
    id: "2022-midbrook-01",
    side: "buyer",
    year: 2022,
    month: 8,
    /* Workbook: Midbrook. Recorded here as Oakwood Acres until 2026-08-17 —
       that name belongs to the Charlotte closing in February. */
    neighborhood: "Midbrook",
    city: "Rock Hill",
    state: "SC",
    /* city is the market */
    market: "rock-hill",
    propertyType: "Single Family",
    /* York County, and a listed SC market as of 2026-08-17 (CLAUDE.md §5). */
    pillars: ["carolinas-border"],
    /* Workbook: "Buyer possesion before close". Possession ahead of closing is
       a real concession and a good example of a lever that is not price at all.
       No figure involved, which keeps it clear of SC non-disclosure too. */
    lever: "Possession granted to the buyer before closing.",
    reviewId: "google-cathy-phillips",
  },
  {
    id: "2022-fieldlark-trails-01",
    side: "buyer",
    year: 2022,
    month: 7,
    neighborhood: "Fieldlark Trails",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: [],
    /* Submarket column: East Charlotte, exact match. */
    market: "east-charlotte",
    reviewId: "google-seth-kuhnau",
  },
  {
    id: "2022-aveline-at-coulwood-01",
    side: "buyer",
    year: 2022,
    /* Closing month. Under contract February 2022, closed April 2022 — the gap
       is the build. The schema records the closing only. */
    month: 4,
    neighborhood: "Aveline at Coulwood",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    builder: "JCB Urban",
    pillars: ["new-construction"],
    /* Submarket column: Northwest Charlotte, exact match. */
    market: "northwest-charlotte",
    /* A hot market and the winning offer went over asking. Deliberately not
       marketed: it is a dollar outcome, and "paid more than asking" is not a
       lever that recommends her. */
    lever:
      "The client would consider no other community. Multiple offers came in on the homesite. Theirs was the one accepted.",
    reviewId: "zillow-saquanna-carter",
  },
  {
    id: "2022-aveline-at-coulwood-02",
    side: "buyer",
    year: 2022,
    month: 4,
    /* Second closing in this community, a different client from -01. The
       workbook confirms the builder, which was open until 2026-08-17. */
    neighborhood: "Aveline at Coulwood",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    builder: "JCB Urban",
    pillars: ["new-construction"],
    /* Submarket column: Northwest Charlotte, exact match. */
    market: "northwest-charlotte",
    reviewId: "zillow-harrist245034",
  },
  {
    id: "2022-hunters-pointe-01",
    side: "buyer",
    year: 2022,
    month: 4,
    neighborhood: "Hunters Pointe",
    city: "Dallas",
    state: "NC",
    propertyType: "Single Family",
    /* Gaston County, outside the markets listed in CLAUDE.md §5. A real
       closing, so it belongs here; it just carries no pillar. */
    pillars: [],
    /* Workbook: "No DDF or EMD". In North Carolina the due diligence fee is
       non-refundable money paid up front, so a contract without one is a
       substantive term, not a technicality — exactly the kind of lever a
       first-time buyer would never know to ask for. */
    lever: "No due diligence fee and no earnest money deposit.",
    reviewId: "zillow-steven-holt",
  },
  {
    id: "2022-shannon-park-01",
    side: "buyer",
    year: 2022,
    month: 4,
    neighborhood: "Shannon Park",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: [],
    /* Submarket column: East Charlotte, exact match. */
    market: "east-charlotte",
    lever: "Seller concessions at closing.",
  },
  {
    id: "2022-belle-vista-01",
    side: "buyer",
    year: 2022,
    month: 3,
    neighborhood: "Belle Vista",
    city: "Charlotte",
    state: "NC",
    propertyType: "Condo",
    pillars: [],
    /* Neighborhood column: "Ballantyne West". */
    market: "ballantyne",
    lever: "Won in a multiple-offer situation.",
  },
  {
    id: "2022-oakwood-acres-01",
    side: "buyer",
    year: 2022,
    month: 2,
    /* Workbook: Oakwood Acres. The linked review's Zillow line says
       "Montclaire". */
    neighborhood: "Oakwood Acres",
    city: "Charlotte",
    state: "NC",
    propertyType: "Single Family",
    pillars: [],
    lever: "Seller concessions at closing.",
    reviewId: "zillow-mckenna-jahns",
  },
  {
    id: "2022-dilworth-01",
    side: "buyer",
    year: 2022,
    month: 2,
    neighborhood: "Dilworth",
    city: "Charlotte",
    state: "NC",
    /* subdivision name is the market name */
    market: "dilworth",
    propertyType: "Condo",
    pillars: [],
    lever: "Purchased under list price, with seller concessions on top.",
  },
  {
    id: "2022-beverly-crest-01",
    side: "buyer",
    year: 2022,
    month: 1,
    /* Workbook: Beverly Crest. The linked review's Zillow line says "Oxford
       Hunt". */
    neighborhood: "Beverly Crest",
    city: "Charlotte",
    state: "NC",
    propertyType: "Townhouse",
    pillars: [],
    lever: "Seller concessions at closing.",
    /* Her first purchase. She returned four years later to buy and sell — see
       zillow-brittany-turner-2026, the strongest retention evidence on site. */
    reviewId: "zillow-brittany-turner-2022",
  },
];
