import type { Metadata } from "next";

import { AGENT, BROKERAGE, SITE_URL } from "@/lib/site";

/**
 * The share card. Generated by scripts/build-og-image.py — see that file for
 * why it is a committed image rather than an ImageResponse, and why it lives in
 * public/ rather than under the app/opengraph-image convention.
 *
 * It is advertising that no test can read: tests/compliance.test.tsx renders
 * pages, and this is a JPEG. The brokerage name, both license numbers, the
 * REALTOR® mark, and the tracking number are drawn into the artwork itself, and
 * it states no dollar figure so no results disclaimer is owed. Regenerate it
 * rather than editing it, and look at it before shipping.
 */
const OG_IMAGE = {
  url: "/og-image.jpg",
  width: 1200,
  height: 630,
  alt: `${AGENT.name}, ${AGENT.title} with ${BROKERAGE.name}. "The other side of the table does this for a living. They know what's askable. Now you do too."`,
} as const;

/**
 * The canonical URL and the Open Graph block for one route, from one path.
 *
 * ---------------------------------------------------------------------------
 * Why this exists, rather than each page writing its own
 *
 * Next merges `openGraph` by REPLACEMENT, not by depth. A page that set
 * `openGraph: { title, description }` therefore silently discarded the `type`,
 * `locale`, `siteName`, and `url` configured in app/layout.tsx — which is how
 * `/` and `/negotiation` shipped with no og:url at all.
 *
 * The pages that did not override it had the opposite problem and it was worse:
 * they inherited the layout's single hardcoded `url: SITE_URL`, so every one of
 * them told a crawler its canonical was the home page. A share of /about was
 * attributed to /.
 *
 * Both failures come from the same cause — the Open Graph URL was written
 * somewhere other than where the path is known. So it is written here, once,
 * beside `alternates.canonical`, from the same argument.
 *
 * tests/metadata.test.ts asserts the two agree on every route.
 * ---------------------------------------------------------------------------
 */
export function routeMetadata({
  path,
  ogTitle,
  ogDescription,
  article,
}: {
  /** Root-relative, leading slash, no trailing slash. `/` for the home page. */
  path: string;
  /** Only when the share card should say something other than the page title. */
  ogTitle?: string;
  /** Only when the share card should say something shorter than the meta description. */
  ogDescription?: string;
  /**
   * Set on posts and area pages, which are articles rather than the site
   * itself. The dates are optional because only posts have them: an area page
   * is evergreen market knowledge with no publication moment, and stamping one
   * on would be a freshness claim nobody can support. Where dates do exist they
   * are the same ones lib/schema.tsx puts in BlogPosting, from the same source.
   */
  article?: { publishedTime?: string; modifiedTime?: string };
}): Pick<Metadata, "alternates" | "openGraph" | "twitter"> {
  const shared = {
    locale: "en_US",
    siteName: AGENT.name,
    /* Absolute, and the same host the site serves from. The apex is canonical
       and www 308s to it, so this must never be built with a "www." — an
       og:url that redirects is half the defect this file was written to fix. */
    url: canonicalUrl(path),
    /* Named explicitly rather than left to the file convention. The convention
       merges the image into each segment's own metadata, so any page declaring
       an `openGraph` block drops it — which is how the card reached only the
       home page the first time it shipped. */
    images: [OG_IMAGE],
    ...(ogTitle ? { title: ogTitle } : {}),
    ...(ogDescription ? { description: ogDescription } : {}),
  };

  /* Without `summary_large_image` the card renders as a 120px thumbnail beside
     the text, which wastes a 1200×630 image built to be read. */
  const twitter: Metadata["twitter"] = {
    card: "summary_large_image",
    images: [OG_IMAGE],
    ...(ogTitle ? { title: ogTitle } : {}),
    ...(ogDescription ? { description: ogDescription } : {}),
  };

  if (article) {
    return {
      alternates: { canonical: path },
      openGraph: { ...shared, type: "article", ...article },
      twitter,
    };
  }

  return {
    alternates: { canonical: path },
    openGraph: { ...shared, type: "website" },
    twitter,
  };
}

/** `/about` → `https://jasminegarcia.com/about`. `/` → the bare origin. */
export function canonicalUrl(path: string): string {
  return path === "/" ? SITE_URL : `${SITE_URL}${path}`;
}
