/**
 * Client reviews — the canonical dataset. Chronological.
 *
 * `body` is verbatim in every case. Do not fix typos, do not tidy grammar, do
 * not shorten to fit a layout. If a review does not fit, the layout is wrong.
 * CLAUDE.md §7.
 *
 * Bylines are recorded exactly as posted so each review stays verifiable
 * against the platform. Nothing renders them — `displayName()` prints first
 * name + last initial.
 *
 * Read lib/reviews/types.ts before adding to this file. Several fields exist
 * to stop specific mistakes, and `openQuestion` is a publication gate.
 */

import type { Review } from "./types";

export const REVIEWS: readonly Review[] = [
  {
    id: "zillow-brittany-turner-2022",
    author: "Brittany turner",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-01-31",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2022,
      location: "Oxford Hunt, Charlotte, NC",
    },
    body: "We used Jasmine for our first home purchase and she was excellent!! She was extremely responsive and helpful with all the plot twists that occur during the home buying process. She was also able to help us negotiate through crazy market prices and secure our home with multiple offers in. Would highly recommend using her if you’re looking to buy a new home.",
    statesDollarOutcome: false,
    note: "First of two. She came back four years later to buy and sell — see zillow-brittany-turner-2026. The pair is the strongest retention evidence on the site.",
  },
  {
    id: "zillow-mckenna-jahns",
    author: "McKenna Jahns",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-02-24",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Montclaire, Charlotte, NC",
    },
    body: "Jasmine was amazing! She was extremely quick to respond, answered all the questions I had as a first time home buyer, and advocated for me to ensure the process moved extremely smoothly. Would absolutely recommend her to anyone looking to purchase a home!",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-saquanna-carter",
    author: "Saquanna Carter",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-04-08",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Single Family",
      year: 2022,
      location: "Coulwood West, Charlotte, NC",
    },
    body: "I am glad we crossed paths with Jasmine. She helped me and my husband find our first brand new home!! Promised to help us find a home and she did. Kept a open line of communication and checked in often. I would recommend her to anyone who is looking for their dream home.",
    statesDollarOutcome: false,
    crossPostedTo:
      "Google, posted as “S Carter” (Local Guide). Opens “Jasmine Garcia was my realtor and I am glad we crossed paths.” — otherwise the same text. Do not add a second entry.",
    note: "Zillow labels this 'Sold' but the client describes buying their first home. The label is Zillow's, not hers — do not surface this one on /sellers on the strength of `role`. Settled 2026-08-17: the transaction record (2022-aveline-at-coulwood-01) is buyer-side new construction, so the client's own account is the accurate one.",
  },
  {
    id: "zillow-harrist245034",
    /* Posted under the generated Zillow handle "harrist245034"; the id keeps it
       so the review stays findable on the platform. The real name is confirmed,
       so the byline is the name — `displayName()` renders "Trevor H." */
    author: "Trevor Harris",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-04-30",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Coulwood West, Charlotte, NC",
    },
    body: "Jasmine was amazing throughout our entire home buying process. Our closing process was extended due to the home being new construction but Jasmine and her team did such a great job keeping us up to date with all necessary information at all times. There was a minor issue towards closing that was handled very well by Jasmine and the rest of the Matt Stone team that we are very appreciative for. We would 100% recommend Jasmine for your home buying process!",
    statesDollarOutcome: false,
    crossPostedTo:
      "A second review by the same client, different wording, recorded in the closed-transactions workbook: “The entire home buying process with the Matt Stone team was very stress-free and very well managed. Our agent Jasmine Garcia was amazing to work with and was willing to help out in any way possible. Our closing process was extended due to the home being under construction and Jasmine and the rest of the Matt Stone team did a great job in keeping us up to date and ensuring we knew everything we needed to know at all times. I would 100% recommend this team, especially Jasmine, for finding your new home!” Platform unconfirmed, presumed Google. Do not add a second entry.",
    note: "Resolved 2026-08-17: the handle is Trevor Harris. A separate Aveline at Coulwood buyer, not the same closing as zillow-saquanna-carter — two different clients in one community. His transaction row is 2022-aveline-at-coulwood-02.",
  },
  {
    id: "zillow-steven-holt",
    author: "Steven Holt",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-05-02",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Dallas, NC",
    },
    body: "Jasmine got me more than I could ask for. Very quick on questions I had through the process. We closed faster than expected. We told Jasmine what we were looking for and within a week we were putting in an offer. Ty",
    statesDollarOutcome: false,
    crossPostedTo:
      "A second review by the same client, different wording, recorded in the closed-transactions workbook: “Jasmine Garcia was great to us. She found a home that we wanted very quickly and answered any questions I had through the house buying process. I highly recommend her. We got more than we asked for. 😊” Platform unconfirmed, presumed Google. Do not add a second entry, and do not merge the two texts — the body above is the verbatim Zillow one.",
  },
  {
    id: "zillow-sms2rcks",
    author: "sms2rcks",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-07-27",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Charlotte, NC",
    },
    body: "Was a pleasure to work with Jasmine! She helped me through the process and was very responsive! The closing was very straightforward & she had many resources we used during the due diligence period!",
    statesDollarOutcome: false,
    openQuestion: "TODO(verify): generic Zillow username. Needs the client's real name.",
  },
  {
    /*
      From the closed-transactions workbook, not from a platform scrape — which
      is why every field about the POSTING is unconfirmed while the words
      themselves are solid. The openQuestion below is the publication gate: the
      review sits in the dataset, joins to its transaction, and stays off the
      site until someone finds the original.
    */
    id: "unverified-harold-cathy-phillips",
    author: "Harold & Cathy Phillips",
    rating: 5,
    platform: "google",
    postedOn: "TODO(verify): unconfirmed. Not among the Zillow reviews already recorded here, so Google is the assumption, not a finding.",
    /* Placeholder: the closing month, NOT the posting date, which nobody has. */
    date: "2022-08-01",
    datePrecision: "month",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Oakwood Acres, Rock Hill, SC",
    },
    body: "It was such a pleasure working with Jasmine Garcia. She understood what we were looking for in a home as well as the current market. She was very attentive to getting answers to questions we had and never left us hanging. We have worked with over 6 realators over the years and Jasmine was by far the best realtor we have worked with. We would highly recommend her to anyone looking to buy or sell a home!",
    statesDollarOutcome: false,
    openQuestion:
      "TODO(verify): platform, posting date, and permalink are all unconfirmed — transcribed from the closed-transactions workbook. The text is quoted as supplied and has not been tidied ('realators' is as written). Confirm against the live review before this publishes, and fix the id once the platform is known. Its transaction row is 2022-midbrook-01.",
  },

  /* ==========================================================================
     TRANSCRIBED FROM THE CLOSED-TRANSACTIONS WORKBOOK, NOT FROM A PLATFORM.

     Every entry below is gated by `openQuestion` for the same reason: the words
     are the client's and are quoted as supplied, but the platform, posting
     date, and permalink are unconfirmed, so nothing here is verifiable against
     a live review yet. `publishableReviews()` filters them out, and the
     transactions ledger will not render a link to one — so they can sit here
     safely until someone works through the list.

     Dates are the CLOSING month as a placeholder, never a known posting date.
     Fix the id prefix once each platform is confirmed.
     ========================================================================== */
  {
    id: "unverified-seth-kuhnau",
    author: "Seth Kuhnau",
    rating: 5,
    platform: "google",
    postedOn: "TODO(verify): unconfirmed.",
    date: "2022-07-01",
    datePrecision: "month",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Fieldlark Trails, Charlotte, NC",
    },
    body: "Jasmine was so great to work with! We found the right property for my budget! Would recommend again and again!",
    statesDollarOutcome: false,
    openQuestion:
      "TODO(verify): platform, posting date, and permalink unconfirmed — transcribed from the workbook. Transaction row 2022-fieldlark-trails-01.",
  },
  {
    id: "unverified-vicki-white",
    author: "Vicki White",
    rating: 5,
    platform: "google",
    postedOn: "TODO(verify): unconfirmed.",
    date: "2022-09-01",
    datePrecision: "month",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2022,
      location: "Park Place, Dallas, NC",
    },
    body: "Jasmine is absolutely wonderful! She was my buyers agent and is so response--her patience is absolutely amazing. We looked at several properties and finally found something suitable, but the listing agent was HORRIFIC (she is the poster child for giving realtors a bad name). Jasmine was so professional and patient--she was the calm voice of reason despite that listing agent's constant drama. I would have walked away from the deal were it not for Jasmine because I can't stand drama. I know that dreadful woman upset Jasmine, she upset everyone so needlessly and treated us like dirt--primarily because I'm a military veteran. Jasmine is a superb realtor who is very knowledgeable and treats people with kindness and respect. She genuinely cares and she gets the job done with zero emotional turmoil. To have handled that outrageous joke of realtor so calmly--I could not have done that! Jasmine is AWESOME and I cannot recommend her enough for all your real estate needs! Retirement is just down the road--and you can bet Jasmine will be selling my property when the time comes!",
    statesDollarOutcome: false,
    openQuestion:
      "DO NOT PUBLISH AS WRITTEN — this is a stronger gate than the transcription problem it shares with its neighbours. The review attacks the opposing agent at length and in identifiable terms ('the poster child for giving realtors a bad name', 'that dreadful woman'), and states the client believes she was mistreated because she is a military veteran. Running it puts a disparaging claim about a real third party into brokerage advertising and pulls a protected characteristic into copy §7 keeps clear of. §7 also forbids altering a testimonial, so it cannot be trimmed into shape — it runs whole or not at all. Needs the BIC and probably counsel. Her closing is in the ledger regardless: transaction row 2022-park-place-01.",
  },
  {
    id: "unverified-cha-ray-calvin-bland",
    author: "Cha'Ray & Calvin Bland",
    rating: 5,
    platform: "google",
    postedOn: "TODO(verify): unconfirmed.",
    date: "2023-05-01",
    datePrecision: "month",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2023,
      location: "Shopton Point, Charlotte, NC",
    },
    body: "Jasmine was our realtor and provided such professionalism and knowledge on the home buying process. She is super sweet and kind and most definitely works in the best interest of the client. She was supportive on our decisions and made the process smooth and worry free.",
    statesDollarOutcome: false,
    openQuestion:
      "TODO(verify): platform, posting date, and permalink unconfirmed — transcribed from the workbook. Transaction row 2023-shopton-point-01.",
  },
  {
    id: "unverified-nuraini-adams",
    /* The closing is recorded under Paul Adams Jr; the review was posted by his
       wife, Nuraini Adams, confirmed 2026-08-19. displayName() renders
       "Nuraini A." */
    author: "Nuraini Adams",
    rating: 5,
    platform: "google",
    postedOn: "TODO(verify): Google, per Bill.",
    date: "2023-09-01",
    datePrecision: "month",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2023,
      location: "Preston Park, Pineville, NC",
    },
    body: "Jasmine Garcia picked up the phone when we called the agency, as recommended by a friend and since then, she became our realtor. We found 5-6 houses that we wanted to view on the same day since we are from out of state and Jasmine helped us to arrange it. She’s very responsive, very helpful and she even helped keep an eye on our toddler when we were touring the houses. We have signed the deed and she’s going to help us with an errand since we have not moved there. That’s definitely above and beyond her job scope and we really appreciate the assistance from her in our house search. Thank you Jasmine!",
    statesDollarOutcome: false,
    openQuestion:
      "TODO(verify): posting date and permalink unrecorded. Posted on Google by Nuraini Adams, wife of the client the closing is recorded under (both confirmed by Bill). Transaction row 2023-preston-park-01.",
  },
  {
    id: "unverified-amy-hood",
    author: "Amy Hood",
    rating: 5,
    platform: "google",
    postedOn: "TODO(verify): unconfirmed.",
    date: "2023-09-01",
    datePrecision: "month",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2023,
      location: "Lancaster, SC",
    },
    body: "Jasmine made the home buying process a positive experience. She was dedicated to helping me find the perfect home to meet all my needs. Questions were answered in a timely manner and requests to tour homes were scheduled almost immediately. Jasmine will definitely be my realtor for any future property purchases.",
    statesDollarOutcome: false,
    openQuestion:
      "TODO(verify): platform, posting date, and permalink unconfirmed — transcribed from the workbook. Transaction row 2023-lancaster-01.",
  },
  {
    id: "unverified-tim-julie-counterman",
    author: "Tim & Julie Counterman",
    rating: 5,
    platform: "google",
    postedOn: "TODO(verify): unconfirmed.",
    date: "2024-03-01",
    datePrecision: "month",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2024,
      location: "Cresswind, Mint Hill, NC",
    },
    body: "Jasmine Garcia is the best! She took the time to really get to know us and what we were looking for in a home. By house #3, she walked in and said, nope, this isn’t for them! She was easy to work with, took our concerns seriously, and landed us our new home! Jasmine was with us every step of the way and helped us when things seemed out of whack with our builder. We would recommend her to anyone without hesitation!!",
    statesDollarOutcome: false,
    openQuestion:
      "TODO(verify): platform, posting date, and permalink unconfirmed — transcribed from the workbook. Transaction row 2024-cresswind-01. Worth prioritising: 'helped us when things seemed out of whack with our builder' is new-construction evidence in a client's own words.",
  },

  {
    id: "zillow-user3842511",
    author: "user3842511",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-08-26",
    datePrecision: "day",
    transaction: {
      role: "bought and sold",
      propertyType: "Single Family",
      year: 2022,
      location: "Rock Hill, SC",
    },
    body: "It was such a pleasure working with Jasmine Garcia. She understood what we were looking for in a home as well as the current market. She was very attentive to getting answers to questions we had and never left us hanging. We have worked with over 6 realators over the years and Jasmine was by far the best realtor we have worked with. We would highly recommend her to anyone looking to buy or sell a home!",
    statesDollarOutcome: false,
    openQuestion: "TODO(verify): generic Zillow username. Needs the client's real name.",
  },
  {
    id: "zillow-cori-halter",
    author: "Cori Halter",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-12-01",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Prosperity Village, Charlotte, NC",
    },
    body: "I cannot say enough about Jasmine Garcia. Her talent for both figuring out the kind of home we wanted and then finding it in record time was simply amazing. To add to the challenge, we are moving to Charlotte from out of state. She remained calm, paid attention to details and was kind, confident and gave us OUTSTANDING service. I will always use her for any future real estate needs.",
    statesDollarOutcome: false,
    sameTransactionAs: ["zillow-kathy-hannan"],
    note: "Same Prosperity Village purchase as Kathy H., reviewed the same day. Do not run both on one page.",
  },
  {
    /**
     * The relocation pillar's anchor. Phoenix buyers, Hurricane Ian showing —
     * docs/BRAND-VOICE.md §5 calls for this exact review on /relocation as
     * direct evidence that everyone at the table is local except the client.
     */
    id: "zillow-kathy-hannan",
    author: "Kathy Hannan",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-12-01",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Prosperity Village, Charlotte, NC",
    },
    body: "Jasmine at Matt Stone Realty was amazing to work with! From 2,000 miles away in Phoenix, she made the home searching and buying process seamless! We flew to Charlotte to get boots on the ground and look at “potential” homes. She knew what we were looking for better than we did! We found the perfect house! Jasmine even came out in torrential rain from Hurricane Ian so we could see the house one more time before we flew back to Phoenix with stars in our eyes! She never missed a beat and has kept an eye on our new home for us until we get there! Thanks Jasmine!",
    statesDollarOutcome: false,
    sameTransactionAs: ["zillow-cori-halter"],
  },
  {
    id: "zillow-shayna-quilty-yoder",
    author: "Shayna Quilty-Yoder",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2022-12-14",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2022,
      location: "Idlewild Farms, Charlotte, NC",
    },
    body: "Jasmine Garcia helped us buy our first home, and she was wonderful. She was proactive about making sure we had all of the information we needed, and was very responsive, even when she was traveling out of the country for a few days. Jasmine demonstrated her knowledge of the area and of the real estate field without ever coming across as pushy. She checked in regularly during the closing process to make sure everything was going smoothly, and even sent us a thoughtful housewarming gift. I've already recommended her to a friend who's looking to buy a home, and I would recommend her to anyone who asks.",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-andrew-korpics",
    author: "Andrew Korpics",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2023-03-16",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2023,
      location: "Rock Hill, SC",
    },
    body: "Jasmine Garcia was the absolute best to work with! Highly professional and made my home search such an enjoyable process. Jasmine is always available and does a fantastic job of giving useful recommendations throughout the process. If you are not using her as your realtor, then you are missing out on one of the best in business!",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-rayraycs",
    author: "rayraycs",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2023-05-19",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2023,
      location: "Charlotte, NC",
    },
    body: "Jasmine was our realtor and provided such professionalism and knowledge on the home buying process. She is super sweet and kind and most definitely works in the best interest of the client. She was supportive on our decisions and made the process smooth and worry free.",
    statesDollarOutcome: false,
    openQuestion: "TODO(verify): generic Zillow username. Needs the client's real name.",
  },
  {
    id: "zillow-maggie-jean",
    /* Posted as "Maggie Jean" — first and middle name. Surname confirmed
       2026-08-17 from the workbook, so displayName() renders "Maggie B." */
    author: "Maggie Jean Brewer",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2023-06-11",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2023,
      location: "Concord, NC",
    },
    body: "Thank you, Jasmine Garcia, for doing all of the virtual tours for us while we were trying to find a house from afar. You were sure to promptly schedule for us and then went above and beyond by taking videos for us and posting them as well. Purchasing a house long distance is quite trying, but we made it work! Please send our many thanks to Andy Wilfong for his thorough communication, quick responses, and steady support as well. We couldn't have done it without you!",
    statesDollarOutcome: false,
    note: "Names Andy Wilfong, a member of the team. He approved the usage 2026-08-10. Cleared to run.",
  },
  {
    id: "zillow-jennifer-garcia",
    author: "Jennifer Garcia",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2023-06-22",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Single Family",
      year: 2023,
      location: "Lancaster, SC",
    },
    body: "Jasmine Garcia was a phenomenal realtor who helped us every step of the way. Helped sell our home fairly quickly but also helped us find our new home. Keep up the great work. Thanks for all your help.",
    statesDollarOutcome: false,
    materialConnection: "Her mother. Confirmed 2026-08-10. The review itself discloses nothing.",
    withheld:
      "Her mother, and unlike her brother's review this one does not say so. The FTC endorsement guides want that connection disclosed, and §7 means we cannot add the words to the client's text. A disclosure printed beside the quote would be legal — the disclosure does not have to live inside the testimonial — but it is not worth it here: the review is four generic sentences that prove nothing the other 30 don't, and a second undisclosed-family review turns one warm gesture into a pattern a competitor could screenshot. Reverse it if she wants it and is willing to run “Jasmine's mother” beside it.",
  },
  {
    /**
     * The strongest relocation review outside the case studies, and one of the
     * few that names a negotiated figure. Florida to the Charlotte metro.
     */
    id: "zillow-tanner-mathewson",
    author: "Tanner Mathewson",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2023-11-14",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2023,
      location: "Mount Holly, NC",
    },
    body: "Our realtor, Jasmine, proved to be an indispensable asset during our relocation from Florida to the Charlotte metro. Upon reaching out to the Matt Stone Team, we were promptly connected with her, and from that point forward, our experience was nothing short of exceptional. She exhibited kindness, expertise, and unwavering availability - even when she was out of town. Jasmine took the time to inform and educate us about the various areas and neighborhoods in Charlotte. Her insights into the current real estate market were invaluable, and she consistently prioritized our needs and desires in a new home. With Jasmine's guidance, we discovered our home in a wonderful neighborhood, providing the perfect setting for our family to settle down. Throughout the entire home-buying process, Jasmine maintained excellent communication with us, ensuring a smooth and transparent experience. One of her standout qualities was her impressive negotiation skills, which ultimately resulted in securing a substantial $20,000 in savings for our new home. We extend our heartfelt gratitude to Jasmine and the Matt Stone Team for contributing to a seamless and successful relocation process. Her dedication and expertise made a significant difference, and we couldn't be more pleased with the outcome.",
    statesDollarOutcome: true,
  },
  {
    id: "zillow-david-godfrey",
    author: "David Godfrey",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2023-12-28",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Single Family",
      year: 2023,
      location: "Charlotte, NC",
    },
    body: "I had the pleasure of being represented by Jasmine Garcia. She was very knowledgeable and attentive to my needs as a seller. She listed my home at a fair price that brought in several potential buyers. The Matt Stone agency is lucky to have her as one of their agents.",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-pavel-volynskiy",
    author: "Pavel Volynskiy",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-02-02",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2023,
      location: "Olde Providence South, Charlotte, NC",
    },
    body: "Had the opportunity to work with Jasmine for the purchase of a recent home. She was great to work with. Super patient and kind as I had many directions I was open to doing and she really took her time to ensure I was satisfied with my purchase at the end of the day. Any questions or concerns I had she was able to answer and follow through with.",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-makena-romagnano",
    author: "Makena Romagnano",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-02-04",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2024,
      location: "Oakdale, Charlotte, NC",
    },
    body: "Jasmine was very helpful and knowledgeable throughout the process! Easy to talk to and she was always accessible when I needed her. Some hiccups along the way happened which were bound to happen but we got through them and I am a homeowner! Thanks Jasmine!",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-zuser20161017085123818",
    /* Posted under the generated Zillow handle "zuser20161017085123818"; the id
       keeps it so the review stays findable. Real name confirmed 2026-08-17
       from the closed-transactions workbook. */
    author: "Jeremy Holzwarth",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-05-19",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2024,
      location: "York Road, Charlotte, NC",
    },
    body: "Jasmine Garcia was FANTASTIC to work with. My fiancée and I were first time buyers moving from Chicago to Charlotte and Jasmine made the process so much easier than I was anticipating. She was responsive, handled my dumb questions with grace, and held our hands through the entire process. Ultimately, she was able to help us find the perfect place, and that's what counts the most! She supported us when interacting with the builder, she was there during the walkthrough to provide an extra pair of trained eyes (and caught things we didn't), and was there to celebrate with us at the closing (with a bottle of champagne!). The experience Jasmine provided us as buyers was wonderful and if you're looking for an agent to partner with you to find what you're looking for, I couldn't recommend her more!",
    statesDollarOutcome: false,
    sameTransactionAs: ["zillow-danielle-bonaccorso"],
    note: "Name resolved 2026-08-17: Jeremy Holzwarth, the other half of the LoSo Terraces purchase (transaction row 2024-loso-terraces-01). Chicago relocation AND new construction — the walkthrough paragraph is unusually specific about what an agent catches that a buyer doesn't. Worth resolving the name for.",
  },
  {
    id: "zillow-danielle-bonaccorso",
    author: "danielle bonaccorso",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-05-19",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2024,
      location: "York Road, Charlotte, NC",
    },
    body: "Just moved into a home that Jasmine Garcia helped us buy. She was a huge help, especially since we were moving from Chicago and needed to do a lot from a distance. She was incredibly responsive to all our questions and very knowledgeable about Charlotte real estate. She listened to what we wanted in a home and made a list of places for us to tour while we were visiting Charlotte for a weekend. We loved what she found for us, and we wound up purchasing a home after just that weekend! She walked us through every step of the process with the seller, knew what questions to ask and what to look for in our walkthroughs. We felt like we were in such great hands the entire time. Jasmine made sure that a stressful process like home buying was smooth and easy. We are so grateful we had her as our agent!",
    statesDollarOutcome: false,
    sameTransactionAs: ["zillow-zuser20161017085123818"],
    note: "The publishable half of the York Road purchase. Strong relocation evidence: one weekend of touring, bought after it.",
  },
  {
    id: "zillow-j-smith",
    author: "j smith",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-05-21",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2024,
      location: "Fort Mill, SC",
    },
    body: "I moved to the area from out of state and my local friend referred me to Jasmine Garcia as a realtor; I'm so glad she did. Jasmine is a true gem. I'm a first time home buyer and she helped and guided me through each step of the way. She was patient and always available for my questions. We closed last week and everything went smoothly from start to finish, I really couldn't have asked for a better experience. Jasmine did a lot of amazing negotiating and communicating. She ended up saving me thousands of dollars on an opendoor property! Most importantly I felt that Jasmine truly wanted me to find a place that I liked and didn't rush or push me to buy anything that wasn't right for me. I absolutely recommend her!",
    statesDollarOutcome: true,
    openQuestion: "TODO(verify): partial name only. Needs the client's real name.",
  },
  {
    id: "zillow-emily-corbin",
    author: "Emily Corbin",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-07-05",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2024,
      location: "Sunset Road, Charlotte, NC",
    },
    body: "We had a fantastic experience working with our realtor, Jasmine Garcia . Her professionalism, knowledge, and dedication were exceptional. As first time home buyers, Jasmine guided us through every step of the home buying process with patience and expertise. She truly listened to our needs and found us the perfect home within our budget. Her negotiation skills were impressive, and she ensured that we got the best deal possible. With her help we secured $12,000 in closing cost incentives, which helped us lock in a 2-1 buydown on our interest rate. Also, all appliances (washer, dryer, & refrigerator) & blinds included. Jasmine’s communication was prompt and clear, keeping us informed at all times. I highly recommend Jasmine to anyone looking to buy or sell a home. Thank you for a seamless and stress-free experience, Jasmine!",
    statesDollarOutcome: true,
    sameTransactionAs: ["zillow-wesley-settles"],
    note: "The single best client-voice illustration of the lead magnet: closing-cost incentives, a 2-1 buydown, appliances, blinds. It is the '19 things besides price' list, itemized by a buyer.",
  },
  {
    id: "zillow-wesley-settles",
    author: "Wesley Settles",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-07-16",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2024,
      location: "Sunset Road, Charlotte, NC",
    },
    body: "Jasmine was great to work with from start to finish. She consistently provided new listings that matched our criteria and kept us informed about the market. Throughout our many home tours, she never pressured us to buy, always assuring us that we would know when we found the right home. She was right—We ultimately purchased a new construction home and secured substantial seller concessions that covered our closing costs and an interest rate buy-down, saving us thousands on our mortgage each year. I highly recommend Jasmine to anyone looking to purchase in the Charlotte metro area and have already referred a friend to her.",
    statesDollarOutcome: true,
    sameTransactionAs: ["zillow-emily-corbin"],
  },
  {
    id: "zillow-stephanie-stanglin",
    author: "Stephanie Stanglin",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-09-11",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2024,
      location: "Moss Creek, Concord, NC",
    },
    body: "Jasmine is the best! I've known her for 9 years, so there was no question who I wanted to reach out to when me and my fiancé were looking for a new home. She went all over the Charlotte metro area for us and really learned what we were looking for. When we found our dream house, Jasmine made the process smooth and kept us informed the whole time. Highly recommend Jasmine to help you find your next home!!",
    statesDollarOutcome: false,
    materialConnection:
      "A nine-year friendship. She discloses it herself in the second sentence, which is what makes the review usable — so it runs whole or not at all.",
  },
  {
    id: "zillow-cc1010100",
    author: "cc1010100",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-09-17",
    datePrecision: "day",
    transaction: {
      role: "bought and sold",
      propertyType: "Single Family",
      year: 2024,
      location: "Rock Hill, SC",
    },
    body: "Jasmine Garcia was the best real estate agent for buying and selling our home. She was diligent on getting us the buyer concessions we wanted and sold our home way above average price per square foot for the area! What more could we ask for? She was a true partner in our real estate decisions. Would recommend her and her firm!",
    statesDollarOutcome: true,
    openQuestion: "TODO(verify): generic Zillow username. Needs the client's real name.",
  },
  {
    id: "zillow-davis-page",
    author: "Davis Page",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-09-17",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2024,
      location: "Montclaire South, Charlotte, NC",
    },
    body: "This was an incredible experience working with Jasmine. She truly checks all of the boxes for somebody that you would want on your side in the house buying process. One of the best things traits that I got to see was her patience. My process went on for about a year, off and on, and she was incredibly understanding as well as supportive. Once we got more serious into the house searching, she was continuing to be patient in making sure I was in the perfect house. Along with finding great options, she is incredibly honest and helpful in the house walk through. Several times she was able to point out different things that weren’t obvious at first glance that could have turned into big problems down the road. To top it off, once you find your house, Jasmine has amazing recommendations she works with to take care of everything from the lending process, insurance options, and housing upgrades. If you have the opportunity to work with Jasmine, you will find yourself happy with the results at the end.",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-rajeev-chhetri",
    author: "Rajeev Chhetri",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-09-25",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2024,
      location: "Fort Mill, SC",
    },
    body: "Jasmine was professional and easy to work with and spot on with her appointments. She helped us find our new home in new state (SC) and also worked with the builders to get the appliances and blinds included in the selling price. It was great working with her to find our new home.",
    statesDollarOutcome: false,
    note: "New construction and the SC side of the line, in three sentences. Good fit for /new-construction or /carolinas-border.",
  },
  {
    id: "zillow-samjbkim",
    author: "samjbkim",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2024-10-08",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2024,
      location: "Prosperity Village, Charlotte, NC",
    },
    body: "Jasmine helped me purchase a rental property in Charlotte. Being an out of state investor, she was fantastic to work with, both professional and responsive. Made our buying process smooth and would recommend her for any RE needs.",
    statesDollarOutcome: false,
    openQuestion: "TODO(verify): generic Zillow username. Needs the client's real name.",
  },
  {
    id: "zillow-user6386616",
    author: "user6386616",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-01-31",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2025,
      location: "Concord, NC",
    },
    body: "Jasmine was instrumental in helping me sell my home and purchase my dream home. I first met her about a year ago, and she maintained regular communication until I was ready to begin touring homes. She was incredibly knowledgeable, pointing out key details and potential concerns with every property we visited. Even when Jasmine wasn’t personally available to show a home, she ensured someone from her team stepped in so we never missed an opportunity. When it came time to submit an offer on our dream home, Jasmine guided us through the entire process with patience and expertise. She also helped us prepare our current home for the market while we were under contract for the next one, connecting us with top-notch vendors and a fantastic lender who made the process seamless. Thanks to Jasmine, we sold our home without offering any seller concessions and purchased our new home with a seller-paid home warranty and all repairs covered. I wholeheartedly recommend Jasmine to anyone in need of real estate services. She is professional, knowledgeable, kind, and relatable—a true asset to anyone navigating the real estate market!",
    statesDollarOutcome: true,
    openQuestion: "TODO(verify): generic Zillow username. Needs the client's real name.",
    note: "Buy-and-sell-at-once, which is the hardest thing a client ever asks for. Archived on the old site as testimonial_a-true-asset-to-anyone-navigating-the-real-estate-market.",
  },
  {
    id: "zillow-cedric-brown",
    author: "Cedric Brown",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-04-08",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Townhouse",
      year: 2025,
      location: "Druid Hills North, Charlotte, NC",
    },
    body: "Jasmine Weaver was excellent to work with in the sale of her first home. In a weird market she was able to get us a closer deal with no seller concessions were under contract in under three weeks with no home warranty given and no transaction complications with a seamless process. To top it all off she negotiated for best deal that allowed us to close quickly. 10/10 recommend working with Jasmine!",
    statesDollarOutcome: true,
    sameTransactionAs: ["zillow-cristina-lopez"],
    note: "Real name confirmed 2026-08-10; posted under the username cbob93. Cleared to run.\n\nThe body calls her Jasmine WEAVER because Weaver is her married name — not an error, and not a discrepancy to resolve. It stays as written. She is licensed and advertises as Jasmine Garcia (NC 334700, SC 125546), so the surname appears nowhere else on this site.",
  },
  {
    id: "zillow-cristina-lopez",
    author: "Cristina Lopez",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-05-01",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Townhouse",
      year: 2025,
      location: "Druid Hills North, Charlotte, NC",
    },
    body: "We had an incredible experience working with Jasmine Garcia. Even though we were living out of state, Jasmine made the entire home-selling process smooth and stress-free. She strategically listed our Charlotte home to attract serious buyers and helped us sell it in under three weeks—without offering any seller concessions or a home warranty. Thanks to her expert negotiation skills and deep knowledge of the local real estate market, we walked away with a fantastic deal and more money in our pockets. Jasmine kept us informed every step of the way, providing outstanding communication and support. If you’re looking to sell your home in Charlotte, we highly recommend choosing Jasmine as your trusted listing agent.",
    statesDollarOutcome: true,
    sameTransactionAs: ["zillow-cedric-brown"],
    note: "The second account of the Druid Hills North sale, and a remote seller — rare and useful for /sellers and /relocation both. Archived as testimonial_cristinamaria-lopez5.",
  },
  {
    id: "zillow-humberto-zambrano",
    author: "Humberto Zambrano",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-05-09",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2025,
      location: "Rock Hill, SC",
    },
    body: "Jasmine is an exceptional real estate agent! From start to finish, she was always available and responsive, showing us homes on our schedule. She guided us through the entire home-buying process and helped us purchase our first home together in Rock Hill, SC—saving us $13,500 in the process. Jasmine worked closely with our lender and closing attorney to ensure a smooth, on-time closing. Most importantly, she was kind, professional, and always kept us informed. If you're looking to buy a home in the Rock Hill or Charlotte area, I highly recommend working with Jasmine!",
    statesDollarOutcome: true,
  },
  {
    id: "zillow-brittani-greene",
    author: "Brittani Greene",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-06-12",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2025,
      location: "Mineral Springs-Rumble Road, Charlotte, NC",
    },
    body: "Jasmine has been working with my husband and I for a year and a half. We made a move from Vermont and wanted to get to know Charlotte before purchasing. She was helpful, knowledgeable, and patient with us through out the entire process. She always made herself available and was quick to respond. I couldn’t have asked for a better realtor. She made a confusing and big decision fun and manageable. We HIGHLY recommend Jasmine!!",
    statesDollarOutcome: false,
    note: "Eighteen months from Vermont. Direct evidence for the relocation page's argument that the useful conversation starts long before the offer.",
  },
  {
    id: "zillow-conrado-valencia",
    author: "Conrado Valencia",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-06-23",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2025,
      location: "Mooresville, NC",
    },
    body: "Happy happy Customer here! We moved a year ago from Miami and we were looking for our forever home in Mooresville NC, Jasmine guided us through the whole process so smoothly and now we are homeowners! Thank you Jasmine!",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-ashley",
    author: "Ashley",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-06-29",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2025,
      location: "Montibello, Charlotte, NC",
    },
    body: "I’m so thankful to had had Jasmine advocating for me as a first time home buyer. She worked with my short timeline and helped me understand the home buying process. Thank you!",
    statesDollarOutcome: false,
    openQuestion: "TODO(verify): first name only. Awaiting last initial.",
  },
  {
    id: "zillow-trey-ishee",
    author: "Trey Ishee",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-07-02",
    datePrecision: "day",
    transaction: { role: "bought", year: 2025 },
    body: "Jasmine is an excellent agent. Thorough, knowledgeable, responsive to questions and concerns. She did an excellent job deal dealing with a difficult agent on my recent purchase. Could not recommend or more highly.",
    statesDollarOutcome: false,
  },
  {
    id: "zillow-keely-alert",
    author: "Keely Alert",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-09-14",
    datePrecision: "day",
    transaction: { role: "bought", year: 2025 },
    body: "From the very beginning, Jasmine made a great first impression on us. She never pressured us, and it was clear right away that she wasn’t just chasing a commission — she genuinely wanted us to find the perfect home. Even while she was traveling out of town, she stayed consistently available, answering our questions quickly and thoughtfully. Jasmine is incredibly resourceful, and when she commits to something, she truly follows through. With the delays we faced in closing, she went to bat for us and ultimately secured a reduced home rate — saving us money! That kind of dedication and advocacy is rare. I would highly recommend Jasmine as your real estate agent. She goes above and beyond for her clients, and you can trust that she’ll have your best interests at heart every step of the way.",
    statesDollarOutcome: true,
  },
  {
    id: "zillow-dias-ismailov",
    author: "Dias Ismailov",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-09-16",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2025,
      location: "Druid Hills South, Charlotte, NC",
    },
    body: "We bought a house with Jasmine Garcia - it was really awesome experience. I didn't feel any pressure and I felt like Jasmine really care about my goals. RE also about money, so some highlights of the purchase: • $20k off of list price • $34k in instant home equity • $22k+ in seller concessions Ofc, it's also up to market condition, but Jasmine has done a great job! Thank you!  P.S. I'm looking to cooperate further with more properties, but for other goals :)",
    statesDollarOutcome: true,
    note: "Three separate dollar figures in one review, and the client himself adds 'it's also up to market condition' — the disclaimer in a buyer's own voice. Requires ResultsDisclaimer adjacent regardless.",
  },
  {
    id: "zillow-sharee-khaldi",
    author: "Sharee Khaldi",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2025-09-25",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Single Family",
      year: 2025,
      location: "Lower Palisades, Charlotte, NC",
    },
    body: "I don’t have enough words to express how grateful I am to Jasmine. After almost 2 years of trials with selling my home Jasmine finally closed the deal. From the very beginning, they she was on it, I had some repairs that were needed (ok, a few more than some), and she connected me with a contractor right away to get the house ready to list. When things popped up as time went on she was there to fix things within hours. I don’t live in the state anymore, and she was my eyes and ears the whole time. No panic, just handled. She hosted open houses, checked in on the house regularly, and kept me in the loop the whole time. On top of everything else, when it comes to negotiations she’s the best of the best. She was able to get me $20k more than the initial offer, pushed for a higher due diligence amount, and even negotiated the repair agreement so I didn’t get stuck with a bunch of costs. I ended up saving (and making!) thousands. Also, my house sold faster than anything else in the neighborhood. Honestly, if you want someone who’s caring, responsive, and genuinely has your back, this is the agent you want. I couldn’t have asked for a better experience. Thank you for everything Jasmine!",
    statesDollarOutcome: true,
    note: "Surname confirmed 2026-08-10. The review docs/CONTENT-PLAN.md flags as the strongest match for the site's whole argument — 'when it comes to negotiations she's the best of the best,' plus a seller who lives out of state and a home that took two years. Worth chasing the last initial.",
  },
  {
    id: "zillow-shay-t",
    author: "Shay T",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2026-02-06",
    datePrecision: "day",
    transaction: { role: "bought", year: 2025 },
    body: "We truly appreciate all of her help throughout our 1st time new home buying process. She was thorough, proactive, and extremely reliable in all of her communication. Initially, we thought we would be able to stay very involved in every step of the new home construction process, but life happened and we became quite busy. Despite that, we never felt stressed or worried because Jasmine consistently kept us informed of every step that needed to be taken. She made sure nothing was missed and guided us through the process seamlessly, so we never had to second-guess anything. If you are looking for someone who will truly take care of you and ensure a smooth process from start to finish, Jasmine is exactly that person. We wish her the very best and are grateful for her support.",
    statesDollarOutcome: false,
    note: "Already posted as first name + last initial. Archived as testimonial_we-never-felt-stressed-or-worried.",
  },
  {
    /**
     * Canonical entry for her brother's review. He posted it to Zillow on
     * 2026-05-15 and to the Stone Realty Group Google page; the Google
     * rendering carries his paragraph breaks, so that is the body kept here.
     * The Zillow posting is what supplies the transaction detail and the exact
     * date — Google only showed "2 months ago".
     */
    id: "google-josh-garcia",
    author: "Josh Garcia",
    rating: 5,
    platform: "google",
    postedOn: "Stone Realty Group",
    date: "2026-05-15",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Townhouse",
      year: 2026,
      location: "Toddville Road, Charlotte, NC",
    },
    body: "When it was time for my fiancée and I to make the leap into homeownership, there was no doubt we wanted to work with my sister, Jasmine Garcia. She was everything I had always heard she was as an agent and more. Jasmine is very knowledgeable about the home buying process, an excellent negotiator, and a great communicator. She always made herself available to answer our questions and never once made us feel overwhelmed or inexperienced during the process.\nFrom start to finish, she guided us every step of the way, helping us secure an amazing lender, homeowner’s insurance, and so much more. She made what could have been a stressful experience feel seamless and exciting, and I truly felt like I never had to worry about anything.\nThe best part was making it to the closing table without having to bring any additional money down and actually receiving a refund back. I truly cannot recommend Jasmine enough for any future homebuyers, especially first time buyers looking for someone they can fully trust and rely on throughout the entire process.",
    statesDollarOutcome: true,
    materialConnection: "Her brother. He discloses it himself in the first sentence.",
    crossPostedTo: "Zillow, 2026-05-15, posted as “Joshua Garcia”. Same text. Do not add a second entry.",
    photoSourceUrl:
      "https://lh3.googleusercontent.com/grass-cs/ACvplmMdw737shNqEY36JmQ24OS7_2UmxDiQqRDsAObGu3QpHcJTf85ZDgDsvbSYGw8fjj4wqrL_9zAxqOKI1F4Dc38FrY_xpHihFMR71Amy3cHNtd48OHyr6lVMLEiyUT4OFxfDQ3eVSPBSi-Y=s3758-w3758-h1696-rw",
  },
  {
    id: "zillow-sophie-fox",
    author: "Sophie Fox",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2026-06-03",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Single Family",
      year: 2026,
      location: "Fort Mill, SC",
    },
    body: "Jasmine Garcia did an amazing job of selling our home. She walked us through the preparation (and has a crew of painters, cleaners and handymen at the ready), gave us a reasonable idea of what to expect, and marketed our home brilliantly. We had multiple offers within 48 hours. She broke down the offers for us and helped us determine which one was the offer with the most favorable terms. She truly understands South Carolina real estate contracts, buyer protections, seller implications, etc. Her negotiation skills are top notch and when tensions arose in negotiations, she was the calming, empowering presence we needed. We could not have asked for a better, more prepared, professional or personable Realtor to help us sell our beloved home. I highly recommend Jasmine Garcia!",
    statesDollarOutcome: false,
    note: "The best evidence on the site for /carolinas-border: a client volunteering that she understands South Carolina contracts specifically. Also a strong /sellers review — 'the offer with the most favorable terms' is the whole thesis that price is not the only variable.",
  },
  {
    id: "zillow-chandler-cordes",
    author: "Chandler Cordes",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2026-06-16",
    datePrecision: "day",
    transaction: {
      role: "sold",
      propertyType: "Single Family",
      year: 2026,
      location: "Huntersville, NC",
    },
    body: "My husband and I worked with Jasmine for nearly two years while searching for our first home, and we couldn't be more grateful for her guidance throughout the process. What stood out most was her patience. At no point did she ever pressure us to make an offer or settle for a home that wasn't 100% right for us. She understood that buying a home is one of the biggest decisions a family can make and always respected our timeline, priorities, and budget. We looked at countless homes over the years, and she remained supportive, responsive, and encouraging every step of the way. And when it came time to negotiate—Jasmine is truly the Queen of Negotiations. Her expertise, strategy, and advocacy were invaluable throughout the process. She helped us navigate a competitive situation, protected our interests every step of the way, and ultimately helped us secure a home that we absolutely love. We always felt like she was in our corner and fighting for the best possible outcome for our future. What started as a professional relationship also turned into a friendship. Over the past two years, Jasmine has been there through so many milestones—she saw us get married, cheered us on through life changes, and was right there celebrating with us when we finally found and purchased our first home. Having someone genuinely invested in your happiness makes all the difference, and we always knew she wanted what was best for us. Buying a home can be stressful, but having someone we trusted made the experience so much easier. We are incredibly thankful for Jasmine's dedication, professionalism, patience, and expertise throughout our home-buying journey. After working with her for two years, we can confidently say she was worth the wait, and we would highly recommend her to anyone looking to buy or sell a home.",
    statesDollarOutcome: false,
    materialConnection:
      "A friendship that grew out of the transaction — she says so herself, and describes Jasmine attending their wedding. Disclosed in the client's own words, so this runs whole or not at all.",
    note: "Contains “Jasmine is truly the Queen of Negotiations.” CLEARED TO RUN, 2026-08-10, by Bill.\n\nThis is the one place that phrase may appear on the site, and only because a client put it there. CLAUDE.md §2's rejection stands for anything in her voice or ours: she does not call herself that here, in copy, in headings, in alt text, or in metadata. A client's verbatim words are not the site making the claim — same logic that lets the case studies say what she cannot.\n\nDo not excerpt this review. Between the title and the disclosed friendship, cropping it either strips a disclosure or turns a client's word choice into a pull quote in our own voice. Whole or not at all.\n\nSeparately: Zillow labels this 'Sold' but they are first-time buyers throughout — do not trust `role` here.",
  },
  {
    id: "zillow-brittany-turner-2026",
    author: "Brittany turner",
    rating: 5,
    platform: "zillow",
    postedOn: "Zillow profile",
    date: "2026-06-25",
    datePrecision: "day",
    transaction: {
      role: "bought and sold",
      propertyType: "Single Family",
      year: 2026,
      location: "Fort Mill, SC",
    },
    body: "This is the second home I’ve purchased with Jasmine and the first house we’ve sold with her. Once again she was phenomenal! Towards closing we had a few issues arise that she navigated excellently and managed to keep the process as smooth as possible. I recommend her to everyone and have had friends use her with the same great experience. You won’t regret reaching out to her",
    statesDollarOutcome: false,
    note: "Second of two, four years after zillow-brittany-turner-2022. A repeat client who also refers friends is worth more than any adjective — run the pair together where the page can carry both dates.",
  },
  {
    /**
     * Canonical entry for the Swecker review. He posted to Zillow on
     * 2026-07-30 and to Google on 2026-08-09 with slightly different opening
     * words — "Jasmine Garcia did an incredible job throughout my whole
     * homebuying process" on Google, "Jasmine did an incredible job throughout
     * the whole homebuying process" on Zillow. Same review, one transaction.
     * The Google text is kept; the Zillow posting supplies the property detail.
     */
    id: "google-matthew-swecker",
    author: "Matthew Swecker",
    rating: 5,
    platform: "google",
    postedOn: "Stone Realty Group",
    date: "2026-08-09",
    datePrecision: "day",
    transaction: {
      role: "bought",
      propertyType: "Single Family",
      year: 2026,
      location: "Windsor Park, Charlotte, NC",
    },
    body: "Jasmine Garcia did an incredible job throughout my whole homebuying process. She was patient and informative while I narrowed my search and provided great insights when I zeroed in on what I was looking for. Never pushy, she wants you to love your home. Her most coveted skill is likely her ability to negotiate. In all, we negotiated about 30k in concessions, including a lower offer price and foundation work the house needed. I would highly recommend her!!",
    statesDollarOutcome: true,
    crossPostedTo:
      "Zillow, 2026-07-30, posted as “Matt Swecker” with minor wording differences. Same transaction. Do not add a second entry.",
    photoSourceUrl:
      "https://lh3.googleusercontent.com/grass-cs/ACvplmMowkJslVxgFNWlRyrC8D-CdTNzJLRxypYpmjzdlKVxDvUCM99N6ZJYJdTRhOibfV2JQMDTb0aUxLW-psvLC7Yea46DK5IeHUm1KJrEbEfbUsfrmixoAxRKHHSLv-iMUxDniA14rn8-eHst=s3758-w3758-h1696-rw",
  },
];
